# Generated by Django 2.2.12 on 2020-08-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='repo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
