# Generated by Django 2.2.12 on 2020-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_github_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='branch',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
