# Generated by Django 2.2.12 on 2020-08-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200817_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='branch',
            field=models.CharField(default='https://github.com', max_length=250),
        ),
    ]
