# Generated by Django 2.2.12 on 2020-08-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200817_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='branch',
            field=models.CharField(default='profile', max_length=250),
        ),
    ]
