# Generated by Django 2.2.12 on 2020-08-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200817_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='branch',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='github',
            name='repo',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
