# Generated by Django 2.2.12 on 2020-08-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200817_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='github',
            name='branch',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='github',
            name='repo',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
