# Generated by Django 2.2.12 on 2020-08-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='createPost',
            new_name='Post',
        ),
    ]
