# Generated by Django 2.2.12 on 2020-08-17 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200817_0313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
