# Generated by Django 2.2.12 on 2020-08-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
