# Generated by Django 2.2.12 on 2020-08-18 07:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code_body',
            field=ckeditor.fields.RichTextField(blank=True, max_length=20000, null=True),
        ),
    ]
